"""Change price datatype in order table

Revision ID: 08465d5e3a2f
Revises: ef31e35ec8bd
Create Date: 2023-10-07 22:59:26.670715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08465d5e3a2f'
down_revision = 'ef31e35ec8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
