"""add book table column migration

Revision ID: 092f196df474
Revises: 368153725d36
Create Date: 2023-10-02 20:33:23.707742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092f196df474'
down_revision = '368153725d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
