"""update tables relationship

Revision ID: 307e0c64aa29
Revises: 65c0b5b789f6
Create Date: 2023-10-03 18:05:16.671240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '307e0c64aa29'
down_revision = '65c0b5b789f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('inventory_count', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_books_user_id_users', type_='foreignkey')
        batch_op.drop_column('image_url')
        batch_op.drop_column('description')
        batch_op.drop_column('user_id')
        batch_op.drop_column('sold')
        batch_op.drop_column('category')

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('shipping_info', sa.String(), nullable=False))
        batch_op.drop_constraint('fk_orders_book_id_books', type_='foreignkey')
        batch_op.drop_column('shippinginfo')
        batch_op.drop_column('book_id')
        batch_op.drop_column('orderdt')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderdt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('shippinginfo', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_orders_book_id_books', 'books', ['book_id'], ['id'])
        batch_op.drop_column('shipping_info')
        batch_op.drop_column('order_date')

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sold', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_books_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('inventory_count')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
