"""add user table column migration

Revision ID: 368153725d36
Revises: 4e069ef50bfe
Create Date: 2023-10-01 19:00:15.280512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368153725d36'
down_revision = '4e069ef50bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usertype', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('usertype')

    # ### end Alembic commands ###
