"""add Tables migration

Revision ID: 4e069ef50bfe
Revises: 3241ef354786
Create Date: 2023-10-01 02:24:01.375609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e069ef50bfe'
down_revision = '3241ef354786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
