"""update tables relationship

Revision ID: 5e18554c199e
Revises: 307e0c64aa29
Create Date: 2023-10-03 18:22:23.085525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e18554c199e'
down_revision = '307e0c64aa29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.TEXT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
