"""update tables relationship

Revision ID: a2ab5076e056
Revises: 0c9372165cfc
Create Date: 2023-10-03 18:36:22.429807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2ab5076e056'
down_revision = '0c9372165cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('sold', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_books_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('inventory_count')
        batch_op.drop_column('genre')

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shippinginfo', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('orderdt', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_orders_book_id_books'), 'books', ['book_id'], ['id'])
        batch_op.drop_column('shipping_info')
        batch_op.drop_column('order_date')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('users_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('shipping_info', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_orders_book_id_books'), type_='foreignkey')
        batch_op.drop_column('book_id')
        batch_op.drop_column('orderdt')
        batch_op.drop_column('shippinginfo')

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('inventory_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_books_user_id_users'), type_='foreignkey')
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('sold')
        batch_op.drop_column('description')
        batch_op.drop_column('category')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
