"""update tables relationship

Revision ID: b759b7d3e876
Revises: e0094dd78700
Create Date: 2023-10-03 15:57:23.299473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b759b7d3e876'
down_revision = 'e0094dd78700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cartitems_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_cartitems_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
