"""remove table column migration

Revision ID: c45dea471f91
Revises: fc4ddc08e26b
Create Date: 2023-10-08 11:14:00.086434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45dea471f91'
down_revision = 'fc4ddc08e26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
